services:
  - type: web
    name: car-stories-frontend
    env: static
    repo: https://github.com/AnatoliiBK/Car-Stories
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build

  - type: web
    name: car-stories-backend
    env: node
    repo: https://github.com/AnatoliiBK/Car-Stories
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
# services:
#   - type: web
#     name: car-stories-frontend
#     env: static
#     repo: https://github.com/AnatoliiBK/Car-Stories
#     branch: main
#     buildCommand: npm install && npm run build
#     staticPublishPath: build

#   - type: web
#     name: car-stories-backend
#     env: node
#     repo: https://github.com/AnatoliiBK/Car-Stories
#     branch: main
#     startCommand: node server.js
#     buildCommand: npm install
#     envVars:
#       - key: MONGODB_URI
#         sync: false
